Tests are green
This error message shows which need to look into

 PASS  src/actions/__tests__/auth.test.js

console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
  Error: Not implemented: navigation (except hash changes)
      at module.exports 
(/Users/toddlangford-archer/Documents/makers/proof-of-work/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
      at navigateFetch 
(/Users/toddlangford-archer/Documents/makers/proof-of-work/node_modules/jsdom/lib/jsdom/living/window/navigation.js:74:3)
      at exports.navigate 
(/Users/toddlangford-archer/Documents/makers/proof-of-work/node_modules/jsdom/lib/jsdom/living/window/navigation.js:52:3)
      at LocationImpl.reload 
(/Users/toddlangford-archer/Documents/makers/proof-of-work/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:230:5)
      at Location.reload 
(/Users/toddlangford-archer/Documents/makers/proof-of-work/node_modules/jsdom/lib/jsdom/living/generated/Location.js:122:25)
      at reload 
(/Users/toddlangford-archer/Documents/makers/proof-of-work/src/actions/auth.js:70:21)
      at Object.dispatch 
(/Users/toddlangford-archer/Documents/makers/proof-of-work/node_modules/redux-thunk/lib/index.js:11:18)
      at Object.dispatch 
(/Users/toddlangford-archer/Documents/makers/proof-of-work/src/actions/__tests__/auth.test.js:98:9)
      at resolve 
(/Users/toddlangford-archer/Documents/makers/proof-of-work/node_modules/jest-jasmine2/build/queue_runner.js:56:12)
      at new Promise (<anonymous>) undefined